### ISSUE TITLE
Why do you choose Kong gateway

### ISSUE THREAD

**Issue by HelloTo4x** [jonashackt/spring-boot-openapi-kong#17]
Hi, i am reading your project, why do you choose Kong gateway in your project instead of Zuul or Spring cloud gateway, can u tell me your purpose, and the pros and cons of Kong gateway if you know, thank you so much

**Comment by jonashackt** [comment]
I wrote about it in this blog https://blog.codecentric.de/en/2020/11/spring-boot-kong/ 
Bottom line: it's not a vs. Spring Cloud, it's more like - if you have Kong, how do you integrate it with Spring Boot in a good way. 
Closing because not really an project issue ;)
